### PR TITLE
MultiPointer Branch Merges

### PR DESCRIPTION
**Pull request by StephenHodgson**
@Railboy Here's the MultiPointer work based off the input refactor so far.

- [x] Remove `PointerInputSource` from `InputSource`, and make Pointers separate from Input Sources.
- [x] Implement Pointers into the `InputSource` and have each `InputSource` keep track of it's internal `pointerId`'s.
- [x] Give ability to name the pointer in constructor, and make the `PointerName` property have get and set capabilities.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@Railboy Added Assets, Prefabs, and MuliPointerTest scene from https://github.com/Railboy/MixedRealityToolkit-Unity/tree/Feature_MultiPointers_Experimental

**Comment by StephenHodgson** [comment]
@Railboy addressed concerns from shiproom meeting last week.

**Comment by Railboy** [comment]
@StephenHodgson I'm getting null reference exceptions and invalid cast exceptions on playmode. Scenes also crash to desktop when I exit playmode.

These I get in the input test scene:
```
NullReferenceException: Object reference not set to an instance of an object
  at HoloToolkit.Unity.InputModule.FocusManager.GetPointerData (IPointer pointer) [0x00043] in C:\Users\v-lasimk\Documents\GitHub\Stephen\MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Focus\FocusManager.cs:391 

InvalidCastException: Cannot cast from source type to destination type.
  at HoloToolkit.Unity.InputModule.BaseCursor.OnSourceLost (HoloToolkit.Unity.InputModule.SourceStateEventData eventData) [0x00002] in C:\Users\v-lasimk\Documents\GitHub\Stephen\MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Cursor\BaseCursor.cs:170
```

In addition I get this in the multi pointers test scene:
```
NullReferenceException: Object reference not set to an instance of an object
  at HoloToolkit.Unity.InputModule.TeleportCursor.CheckCursorState () [0x00014] in C:\Users\v-lasimk\Documents\GitHub\Stephen\MixedRealityToolkit-Unity\Assets\HoloToolkit\Input\Scripts\Cursor\TeleportCursor.cs:23 
```

**Comment by StephenHodgson** [comment]
I'll be sure to address those.

I didn't get a chance to fully review and work this out yet.

**Comment by StephenHodgson** [comment]
Yeah, part of the problem was that I haven't actually done a pass on the prefabs themselves. I'll be sure to address this asap.  I'll let you know once it's ready for testing.

I was mainly interested in a review of the code architecture changes.

**Pull request merged**
