### PR TITLE
Renamed Visualizer to Proxy 

### PR DESCRIPTION
**Pull request by Ecnassianer**
This is a rebased version on the most recent changes

### CODE REVIEW

**Review by StephenHodgson — COMMENTED** [review]
What about all the other places in th toolkit where we use visualisation instead of proxy?

**Comment by StephenHodgson** [comment]
@SimonDarksideJ thoughts?

**Comment by Ecnassianer** [comment]
You mean like the Boundary Visualizer? I looked at all the other occurances of "visual*" and it felt like that was really the only borderline case (obviously we use "visual*" in other places as well, like the touchpad visualizer, but that kind of usage seemed clearly nothing more than a visualization tool). 

I declined to update the Boundary Visualizer because it seemed like something that really was only visualizing a virtual object, and not proxying in all the properties of a real world object. I see arguments for both sides, and ultimately I think "Boundary Visualizer" fits what it does much better than "Controller Visualizer" fit the Controller Proxy, so I'm ambivalent to either Boundary Visualizer or Boundary Proxy.

**Comment by StephenHodgson** [comment]
Idk it definitely seems like we're doing the exact same thing there.

I feel like the boundary is a physical thing seeing as you have to manually set it up irl.

Mostly I'm just asking to create a task to update and standardize the names and terminology of things of this nature.

**Comment by StephenHodgson** [comment]
Obviously we wouldn't want to put it in this PR as it over steps the scope

**Comment by Ecnassianer** [comment]
Like I said, I could go either way. But can you create the task? Other than the changes I just made, I don't know what names and terminology you want to be updated or standardized.

**Comment by SimonDarksideJ** [comment]
Tough one.

A "Proxy" by definition, is an agent working on behalf of another entity.
A "Visualizer" drives the purpose of the act of visualizing, or seeing something visualized.  Presenting the visual representation of something.

Now I would say the ControllerPoseSynchronizer is an Agent, it relays and controls the direction from the controller in to an object in the scene.

This concept, is adding a visual representation on top of the ControllerPoseSynchronizer in to the scene.

**Comment by Ecnassianer** [comment]
Stating those definitions explicitly is really helpful!

**Comment by Ecnassianer** [comment]
This is slightly tangential to this PR, but what do you think of refining the definition of Proxy in the context of MRTK to be "an agent working on behalf of an entity in the device layer"?

**Comment by SimonDarksideJ** [comment]
That's a fair aside @Ecnassianer , however that would only apply to the controllerposesynchroniser.  I believe we have other "Proxy" style handlers in the MRTK, for instance the BoundaryManager or even the Pointers :D

**Comment by StephenHodgson** [comment]
Very good points Simon

**Comment by Ecnassianer** [comment]
What are the Pointers?

**Pull request closed without merging**
